Repository wecode-bootcamp-korea/10-Oh29-ya-frontend, pull requests merged in 2020-07, with the labels that each got.

#4 Add : 스크롤에 따라 달라지는 navbar 구현
  public/Images/appleLogo.png
  public/Images/facebookLogo.png
  public/Images/kakaoLogo.png
  public/Images/logoRectangle.PNG
  public/Images/logoSquare.PNG
  public/Images/naverLogo.png
  public/index.html
  src/Components/AlternatingNav/AlternatingNav.js
  src/Components/AlternatingNav/HeaderNav/HeaderNav.js
  src/Components/AlternatingNav/HeaderNav/HeaderNav.scss
  src/Components/AlternatingNav/Nav/Nav.js
  src/Components/AlternatingNav/Nav/Nav.scss
  src/Components/AlternatingNav/navData.js
  src/Pages/Join/Join.js
  src/Pages/Join/Join.scss
  src/Pages/TwentyNineTV/TwentyNineTV.js
  src/Pages/TwonineTV/TwonineTV.js
  src/Routes.js
  src/index.js
  yarn.lock
Labels: Status: Accepted

#2 Refactor : Login 페이지 구현 완료
  src/Components/AlternatingNav/AlternatingNav.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/snsLoginData.js
  src/Routes.js
Labels: Status: 리뷰 요청

#5 Add : Footer html, css 구현
  public/index.html
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Routes.js
Labels: Status: Accepted

#1 Add : 29TV 페이지/모달창 구현
  README.md
  package-lock.json
  public/data/data.json
  src/Components/ActiveLikeBtn/ActiveLikeBtn.js
  src/Components/ActiveLikeBtn/ActiveLikeBtn.scss
  src/Pages/TwentyNineTV/FeedModal.js
  src/Pages/TwentyNineTV/FeedModal.scss
  src/Pages/TwentyNineTV/SnsModal.js
  src/Pages/TwentyNineTV/SnsModal.scss
  src/Pages/TwentyNineTV/TwentyNineTV.js
  src/Pages/TwentyNineTV/TwentyNineTV.scss
  src/Pages/TwentyNineTV/TwentyNineTVFeedComponent.js
  src/Routes.js
  src/index.js
Labels: Status: 수정 요청

#6 Add: Special Order 페이지 구현
  public/Images/Oh29ya.jpg
  public/Images/orderImg1.jpg
  public/Images/orderImg2.jpg
  public/Images/orderImg3.jpg
  public/Images/orderImg4.jpg
  public/Images/orderImg5.jpg
  public/Images/orderImg6.jpg
  src/Components/AlternatingNav/HeaderNav/HeaderNav.scss
  src/Components/AlternatingNav/Nav/Nav.scss
  src/Components/SpecialContent/SpecialContent.js
  src/Components/SpecialContent/SpecialContent.scss
  src/Pages/SpecialOrder/SpecialOrder.js
  src/Pages/SpecialOrder/SpecialOrder.scss
  src/Pages/SpecialOrder/itemListData.js
  src/Routes.js
Labels: Status: 리뷰 요청

#8 Add: 상품 상세 페이지 구현
  public/Images/bear.jpg
  src/Pages/DetailProduct/DetailProduct.js
  src/Pages/DetailProduct/DetailProduct.scss
  src/Pages/Login/Login.js
  src/Routes.js
Labels: Status: 리뷰 요청

#3 Add: Product페이지 파일 및 컴포넌트 생성
  package-lock.json
  package.json
  public/Images/left-solid.svg
  public/Images/right-solid.svg
  src/Pages/Product/BrandName/BrandName.js
  src/Pages/Product/MainWrap/CategorySection/CategorySection.js
  src/Pages/Product/MainWrap/CategorySection/CategorySection.scss
  src/Pages/Product/MainWrap/CategoryTwoBanner/CategoryTwoBanner.js
  src/Pages/Product/MainWrap/CategoryTwoBanner/CategoryTwoBanner.scss
  src/Pages/Product/MainWrap/CategoryTwoBanner/TwoBannerItem/TwoBannerItem.js
  src/Pages/Product/MainWrap/CategoryTwoBanner/TwoBannerItem/TwoBannerItem.scss
  src/Pages/Product/MainWrap/MainLeftNav/LeftNav/LeftNav.js
  src/Pages/Product/MainWrap/MainLeftNav/MainLeftNav.js
  src/Pages/Product/MainWrap/MainLeftNav/MainLeftNav.scss
  src/Pages/Product/MainWrap/MainSlider/MainSlider.js
  src/Pages/Product/MainWrap/MainSlider/MainSlider.scss
  src/Pages/Product/MainWrap/MainWrap.js
  src/Pages/Product/MainWrap/MainWrap.scss
  src/Pages/Product/Product.js
  src/Pages/Product/Product.scss
  src/Pages/Product/ProductComponent/ProductComponent.js
  src/Pages/Product/TabSwiper/TabSwiper.js
  src/Styles/common.scss
Labels: Status: 추가 기능 구현중

#7 Add : My Heart 페이지 구현
  src/Components/Footer/Footer.scss
  src/Pages/MyHeart/FavListBrand.js
  src/Pages/MyHeart/FavListPost.js
  src/Pages/MyHeart/FavListProduct.js
  src/Pages/MyHeart/FavListTwoNineTV.js
  src/Pages/MyHeart/MyHeart.js
  src/Pages/MyHeart/MyHeart.scss
  src/Pages/TwentyNineTV/FeedModal.scss
  src/Pages/TwentyNineTV/TwentyNineTV.scss
  src/Routes.js
Labels: Status: 수정 요청

#9 Refactor : 리뷰 반영 및 리팩토링
  src/Components/ActiveLikeBtn/ActiveLikeBtn.js
  src/Pages/TwentyNineTV/FeedModal.js
  src/Pages/TwentyNineTV/FeedModal.scss
  src/Pages/TwentyNineTV/TwentyNineTV.js
  src/Pages/TwentyNineTV/TwentyNineTV.scss
  src/Pages/TwentyNineTV/TwentyNineTVFeedComponent.js
  src/config.js
Labels: Status: Accepted

#10 Add: ProductList 페이지
  public/data/product.json
  src/Pages/ProductList/CategoryList/CategoryItem/CategoryItem.js
  src/Pages/ProductList/CategoryList/CategoryItem/CategoryItem.scss
  src/Pages/ProductList/CategoryList/CategoryList.js
  src/Pages/ProductList/CategoryList/CategoryList.scss
  src/Pages/ProductList/FilterNav/FilterNav.js
  src/Pages/ProductList/FilterNav/FilterNav.scss
  src/Pages/ProductList/LeftNav/LeftNav.js
  src/Pages/ProductList/LeftNav/LeftNav.scss
  src/Pages/ProductList/ProductItem/ProductItem.js
  src/Pages/ProductList/ProductItem/ProductItem.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
Labels: Status: Accepted

#13 Refactor : 중간 발표 이후 전체 리팩토링
  src/Components/AlternatingNav/HeaderNav/HeaderNav.js
  src/Pages/Product/MainWrap/MainSlider/MainSlider.scss
  src/Pages/Product/MainWrap/MainWrap.scss
  src/Pages/ProductList/LeftNav/LeftNav.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/SpecialOrder/SpecialOrder.scss
Labels: Status: 리뷰 요청

#18 Add: Women 카테고리 추가
  src/Pages/Women/MainWrap/CategorySection/CategorySection.js
  src/Pages/Women/MainWrap/CategorySection/CategorySection.scss
  src/Pages/Women/MainWrap/CategoryTwoBanner/CategoryTwoBanner.js
  src/Pages/Women/MainWrap/CategoryTwoBanner/CategoryTwoBanner.scss
  src/Pages/Women/MainWrap/CategoryTwoBanner/TwoBannerItem/TwoBannerItem.js
  src/Pages/Women/MainWrap/CategoryTwoBanner/TwoBannerItem/TwoBannerItem.scss
  src/Pages/Women/MainWrap/MainLeftNav/LeftNav/LeftNav.js
  src/Pages/Women/MainWrap/MainLeftNav/MainLeftNav.js
  src/Pages/Women/MainWrap/MainLeftNav/MainLeftNav.scss
  src/Pages/Women/MainWrap/MainSlider/MainSlider.js
  src/Pages/Women/MainWrap/MainSlider/MainSlider.scss
  src/Pages/Women/MainWrap/MainWrap.js
  src/Pages/Women/MainWrap/MainWrap.scss
  src/Pages/Women/Women.js
  src/Pages/Women/Women.scss
  src/Pages/Women/data/categoryData.js
  src/Pages/Women/data/womenItemData.js
  src/Routes.js
Labels: Status: 리뷰 요청

#14 Add : Special-Order 페이지 구현
  src/Components/AlternatingNav/HeaderNav/HeaderNav.js
  src/Components/AlternatingNav/HeaderNav/HeaderNav.scss
  src/Components/AlternatingNav/Nav/Nav.js
  src/Components/AlternatingNav/Nav/Nav.scss
  src/Components/AlternatingNav/navData.js
  src/Components/DetailItem/DetailItem.js
  src/Components/DetailItem/DetailItem.scss
  src/Components/SpecialContent/SpecialContent.js
  src/Components/SpecialContent/SpecialContent.scss
  src/Pages/DetailProduct/DetailProduct.js
  src/Pages/DetailProduct/DetailProduct.scss
  src/Pages/Join/Join.js
  src/Pages/Join/Join.scss
  src/Pages/Join/JoinEmail.js
  src/Pages/Join/JoinEmail.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/SnsLogin/SnsLogin.js
  src/Pages/Login/SnsLogin/SnsLogin.scss
  src/Pages/Login/SnsLogin/snsLoginData.js
  src/Pages/Login/ip.js
  src/Pages/SpecialOrder/SpecialOrder.js
  src/Pages/SpecialOrder/SpecialOrder.scss
  src/Routes.js
  src/Styles/common.scss
  src/config.js
  yarn.lock
Labels: Status: 리뷰 요청

#19 Refactor : heart 아이콘 state 연동 기능 구현 및 리팩토링 완료
  src/Components/ActiveLikeBtn/ActiveLikeBtn.js
  src/Pages/ProductList/CategoryList/CategoryItem/CategoryItem.js
  src/Pages/ProductList/ProductItem/ProductItem.js
  src/Pages/ProductList/ProductList.js
  src/Pages/TwentyNineTV/FeedModal.js
  src/Pages/TwentyNineTV/TwentyNineTV.js
  src/Pages/TwentyNineTV/TwentyNineTV.scss
  src/Pages/TwentyNineTV/TwentyNineTVFeedComponent.js
  src/config.js
Labels: Status: 리뷰 요청

#20 SpecialOrder 페이지 구현
  package.json
  src/Components/AlternatingNav/Nav/Nav.js
  yarn.lock
Labels: Status: Accepted

#15 Add : 백엔드와 통신 후 29TV FavFeed 데이터 불러오기 완료 및 Product 항목 데이터 렌더링 구현중
  src/Pages/MyHeart/FavListBrand.js
  src/Pages/MyHeart/FavListPost.js
  src/Pages/MyHeart/FavListProduct.js
  src/Pages/MyHeart/FavListProduct.scss
  src/Pages/MyHeart/FavListTwoNineTV.js
  src/Pages/MyHeart/MyHeart.js
  src/Pages/MyHeart/MyHeart.scss
  src/Pages/ProductList/ProductItem/ProductItem.js
  src/Pages/TwentyNineTV/FeedModal.js
  src/Pages/TwentyNineTV/FeedModal.scss
  src/Pages/TwentyNineTV/TwentyNineTV.js
  src/Pages/TwentyNineTV/TwentyNineTV.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#16 Add: 장바구니 페이지 구현
  public/data/cartData.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/CartItem/CartItem.js
  src/Pages/Cart/CartItem/CartItem.scss
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: 수정 요청

#22 Add : 상세페이지 좋아요 기능 구현 완료
  src/Components/ActiveLikeBtn/ActiveLikeBtn.js
  src/Components/DetailItem/DetailItem.js
  src/Components/SpecialContent/SpecialContent.js
  src/Components/SpecialContent/SpecialContent.scss
  src/Pages/Join/JoinEmail.js
  src/Pages/Login/Login.js
  src/Pages/Login/ip.js
  src/Pages/SpecialOrder/SpecialOrder.js
  src/Pages/TwentyNineTV/TwentyNineTV.js
  src/config.js
Labels: Status: Accepted

#24 Refactor : 화면 비율에 따라 달라지는 scss수정
  src/Components/ActiveLikeBtn/svg/ActiveIcon.js
  src/Components/ActiveLikeBtn/svg/UnActiveIcon.js
  src/Pages/MyHeart/FavListBrand.js
  src/Pages/MyHeart/FavListPost.js
  src/Pages/MyHeart/MyHeart.js
  src/Pages/MyHeart/MyHeart.scss
  src/Pages/TwentyNineTV/FeedModal.js
  src/Pages/TwentyNineTV/FeedModal.scss
  src/Pages/TwentyNineTV/TwentyNineTV.scss
Labels: Status: 리뷰 요청

#25 최종 발표 전 수정
  package-lock.json
  src/Components/config.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/CartItem/CartItem.js
  src/Pages/ProductList/FilterNav/FilterNav.js
  src/config.js
Labels: Status: Accepted
